# динамический инвентарь из gcp, группировка по сетевым тегам
plugin: google.cloud.gcp_compute
projects:
  - tgops-prod
zones:
  - europe-west3-a
auth_kind: application
keyed_groups:
  - key: networkInterfaces[0].networkIP
    prefix: ip
  - key: (tags.items | default([]))
    prefix: tag
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].networkIP
