# динамический инвентарь из gcp, группировка по сетевым тегам
# ansible_host не задаём, остаётся имя инстанса, по нему idёт iap туннель
plugin: google.cloud.gcp_compute
projects:
  - tgops-prod
zones:
  - europe-west3-a
auth_kind: application
hostnames:
  - name
keyed_groups:
  - key: tags.items | default([])
    prefix: tag
    separator: _
